//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinCatAdsTool.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwinCatAdsTool.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Graph.
        /// </summary>
        public static string AddGraph {
            get {
                return ResourceManager.GetString("AddGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite the LiveVariables on the PLC?.
        /// </summary>
        public static string AreYouSureYouWantToOverwriteTheLiveVariablesOnThePLC {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToOverwriteTheLiveVariablesOnThePLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connected to device {0} with address  {1} .
        /// </summary>
        public static string ClientConnectedToDevice0WithAddress1 {
            get {
                return ResourceManager.GetString("ClientConnectedToDevice0WithAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete Observer for symbol {0}.
        /// </summary>
        public static string CouldNotDeleteObserverForSymbol0 {
            get {
                return ResourceManager.GetString("CouldNotDeleteObserverForSymbol0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register Observer for Symbol {0}.
        /// </summary>
        public static string CouldNotRegisterObserverForSymbol0 {
            get {
                return ResourceManager.GetString("CouldNotRegisterObserverForSymbol0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reload variables.
        /// </summary>
        public static string CouldNotReloadVariables {
            get {
                return ResourceManager.GetString("CouldNotReloadVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update Tree.
        /// </summary>
        public static string CouldNotUpdateTree {
            get {
                return ResourceManager.GetString("CouldNotUpdateTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed timespan.
        /// </summary>
        public static string DisplayedTimespan {
            get {
                return ResourceManager.GetString("DisplayedTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter symbolname to search.
        /// </summary>
        public static string EnterSymbolnameToSearch {
            get {
                return ResourceManager.GetString("EnterSymbolnameToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during load of file.
        /// </summary>
        public static string ErrorDuringLoadOfFile {
            get {
                return ResourceManager.GetString("ErrorDuringLoadOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during search.
        /// </summary>
        public static string ErrorDuringSearch {
            get {
                return ResourceManager.GetString("ErrorDuringSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not have the same structure as the Plc.
        /// </summary>
        public static string FileDoesNotHaveTheSameStructureAsThePlc {
            get {
                return ResourceManager.GetString("FileDoesNotHaveTheSameStructureAsThePlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from file.
        /// </summary>
        public static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load of File {0} was succesful.
        /// </summary>
        public static string LoadOfFile0Wasuccesful {
            get {
                return ResourceManager.GetString("LoadOfFile0Wasuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display.
        /// </summary>
        public static string NoItemsToDisplay {
            get {
                return ResourceManager.GetString("NoItemsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Confirmation.
        /// </summary>
        public static string OverwriteConfirmation {
            get {
                return ResourceManager.GetString("OverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read from PLC.
        /// </summary>
        public static string ReadFromPLC {
            get {
                return ResourceManager.GetString("ReadFromPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only Value.
        /// </summary>
        public static string ReadOnlyValue {
            get {
                return ResourceManager.GetString("ReadOnlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Persistent Variables.
        /// </summary>
        public static string ReadPersistentVariables {
            get {
                return ResourceManager.GetString("ReadPersistentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh data from PLC.
        /// </summary>
        public static string RefreshDataFromPLC {
            get {
                return ResourceManager.GetString("RefreshDataFromPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Graph.
        /// </summary>
        public static string RemoveGraph {
            get {
                return ResourceManager.GetString("RemoveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Backup to {0}.
        /// </summary>
        public static string SavedBackupTo0Logging {
            get {
                return ResourceManager.GetString("SavedBackupTo0Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        public static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol {0} has already been added to the list of observables.
        /// </summary>
        public static string TheSymbol0HasAlreadyBeenAddedToTheListOfObservables {
            get {
                return ResourceManager.GetString("TheSymbol0HasAlreadyBeenAddedToTheListOfObservables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type is not implemented..
        /// </summary>
        public static string ThisTypeIsNotImplemented {
            get {
                return ResourceManager.GetString("ThisTypeIsNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is Read Only.
        /// </summary>
        public static string ThisValueIsReadOnly {
            get {
                return ResourceManager.GetString("ThisValueIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to write JSON {0} with value {1}.
        /// </summary>
        public static string TryingToWriteJSON0WithValue1 {
            get {
                return ResourceManager.GetString("TryingToWriteJSON0WithValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to write to {0} with value {1}.
        /// </summary>
        public static string TryingToWriteTo0WithValue1 {
            get {
                return ResourceManager.GetString("TryingToWriteTo0WithValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated left TextBox.
        /// </summary>
        public static string UpdatedLeftTextBox {
            get {
                return ResourceManager.GetString("UpdatedLeftTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated RestoreView.
        /// </summary>
        public static string UpdatedRestoreView {
            get {
                return ResourceManager.GetString("UpdatedRestoreView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated right TextBox.
        /// </summary>
        public static string UpdatedRightTextBox {
            get {
                return ResourceManager.GetString("UpdatedRightTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
